# Generated by Django 5.2.7 on 2025-11-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misclassification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="misclassificationlog",
            name="references",
            field=models.TextField(null=True),
        ),
    ]
